'use strict';

module.exports = {
  "1/1":"If you give people nothingness, they can ponder what can be achieved from that nothingness. Tadao Ando | Architect",
  "1/2":"Less is more. Mies van der Rohe | Architect",
  "1/3":"We are what we repeatedly do. Excellence then, is not an act, but a habit. Aristotle | Philosopher",
  "1/4":"People tend not to use this word beauty because it\'s not intellectual - but there has to be an overlap between beauty and intellect. Tadao Ando | Architect",
  "1/5":"The longer I live, the more beautiful life becomes. If you foolishly ignore beauty, you will soon find yourself without it. Your life will be impoverished. But if you invest in beauty, it will remain with you all the days of your life. Frank Lloyd Wright | Architect",
  "1/6":"In the big picture, architecture is the art and science of making sure that our cities and buildings fit with the way we want to live our lives. Bjarke Ingels | Architect",
  "1/7":"Design is not for philisophy. Issey Miyake | Designer",
  "1/8":"A designer knows he has achieved perfection not when there is nothing left to add, but when there is nothing left to take away. Antoine de Saint-Exupéry | Writer",
  "1/9":"I would like my architecture to inspire people to use their own resources, to move into the future. Tadao Ando | Architect",
  "1/10":"Digital design is like painting, except the paint never dries. Neville Brody | Graphic Designer",
  "1/11":"The architect represents neither a Dionysian nor an Apollinian condition: here it is the mighty act of will, the will which moves mountains, the intoxication of the strong will, which demands artistic expression. The most powerful men have always inspired the architects; the architect has always been influenced by power. Friedrich Nietzsche | Philosopher",
  "1/12":"Less is a bore. Robert Venturi | Architect",
  "1/13":"Socrates said, \"Know thyself.\" I say, \"Know thy users.\" And guess what? They don\'t think like you do. Joshua Brewer | Graphic Designer",
  "1/14":"I know what women look good in. I don\'t think the rules ever change. Michael Kors | Fashion Designer",
  "1/15":"Our opportunity, as designers, is to learn how to handle the complexity, rather than shy away from it, and to realize that the big art of design is to make complicated things simple. Tim Parsey | Web designer",
  "1/16":"Everything is designed. Few things are designed well. Brian Reed | Comic Book Writer",
  "1/17":"Subversive, ethical, ecological, political, humorous ... this is how I see my duty as a designer. Philippe Starck | Designer",
  "1/18":"To provide meaningful architecture is not to parody history, but to articulate it. Daniel Libeskind | Architect",
  "1/19":"We have to replace beauty, which is a cultural concept, with goodness, which is a humanist concept. Philippe Starck | Designer",
  "1/20":"The life of a designer is one of fight: fight against the ugliness. Massimo Vignelli | Designer",
  "1/21":"Nothing in this world is more simple and more cheap than making cities that provide better for people. Jan Gehl | Architect",
  "1/22":"The public is more familiar with bad design than good design. It is, in effect, conditioned to prefer bad design, because that is what it lives with. The new becomes threatening, the old reassuring. Paul Rand | Graphic Designer",
  "1/23":"People ignore design that ignores people. Frank Chimero | Graphic Designer",
  "1/24":"If you are not able to transmit what you\'re trying to achieve to your collaborators, you will only have minions - or morons. Bjarke Ingels | Architect",
  "1/25":"Every child is an artist. The problem is how to remain an artist once we grow up. Pablo Picasso | Artist",
  "1/26":"Fashion is what you\'re offered four times a year by designers. And style is what you choose. Lauren Hutton | Fashion Designer",
  "1/27":"I understand that, today, some developers are asking architects to design eye-catching, iconic buildings. Fortunately, I\'ve not had that kind of client so far. Fumihiko Maki | Architect",
  "1/28":"The Sun does not realise how wonderful it is until after a room is made. Louis I. Kahn | Architect",
  "1/29":"Design our world so that we have positive social and environmental side effects. Bjarke Ingels | Architect",
  "1/30":"You either know fashion or you don\'t. Anna Wintour | Fashion Designer",
  "1/31":"Good design is all about making other designers feel like idiots because the idea wasn\'t theirs. Frank Chimero | Graphic Designer",
  "2/1":"Design should never say, \"Look at me!\" It should always say, \"Look at this!\" David Craib | Graphic Designer",
  "2/2":"Logic will get you from A to B. Imagination will take you anywhere. Albert Einstein | Scientist",
  "2/3":"Architecture is the will of an epoch translated into space. Mies van der Rohe | Architect",
  "2/4":"You can never take too much care over the choice of your shoes. Too many women think that they are unimportant, but the real proof of an elegant woman is what is on her feet. Christian Dior | Fashion Designer",
  "2/5":"Good design is obvious. Great design is transparent. Joe Sparano | Designer",
  "2/6":"Shoes transform your body language and attitude. They lift you physically and emotionally. Christian Louboutin | Fashion Designer",
  "2/7":"Good architecture is like a good therapy session, a good marriage, a good poem - gently and almost invisibly allowing you to be you, as flawed and as beautiful as you are. Robert Sullivan | Architect",
  "2/8":"In pure architecture the smallest detail should have a meaning or serve a purpose. Augustus W. N. Pugin | Architect",
  "2/9":"The most innovative designers consciously reject the standard option box and cultivate an appetite for thinking wrong. Marty Neumeier | Writer",
  "2/10":"I\'ve noticed the computer sometimes leads to rather bland decision-making; Now, anybody can do a wobbly, blobby building. Peter Cook | Architect",
  "2/11":"What I\'ve done, Coco Chanel would never have done. She would have hated it. Karl Lagerfeld | Fashion Designer",
  "2/12":"I want to make beautiful things, even if nobody cares, as opposed to ugly things. That\'s my intent. Saul Bass | Graphic Designer",
  "2/13":"Creativity takes courage. Henri Matisse | Artist",
  "2/14":"Trendy is the last stage before tacky. Karl Lagerfeld | Fashion Designer",
  "2/15":"Design creates culture. Culture shapes values. Values determine the future. Robert L. Peters | Designer",
  "2/16":"Architecture is the art of how to waste space. Philip Johnson | Architect",
  "2/17":"Walk like you have three men walking behind you. Oscar de la Renta | Fashion Designer",
  "2/18":"I am sure that, as a woman, I can do a very good skyscraper. Zaha Hadid | Architect",
  "2/19":"Fashion is not necessarily about labels. It\'s not about brands. It\'s about something else that comes from within you. Ralph Lauren | Fashion Designer",
  "2/20":"Architecture is a dangerous mix of power and importance. Rem Koolhaas | Architect",
  "2/21":"My juicer is not meant to squeeze lemons; it is meant to start conversations. Philippe Starck | Designer",
  "2/22":"Painting is self-discovery. Every good artist paints what he is. Jackson Pollock | Artist",
  "2/23":"A great building must begin with the immeasurable, must go through measurable means when it is being designed, and in the end must be unmeasured. Louis I. Kahn | Architect",
  "2/24":"A bit of advice, don\'t copy nature too closely. Art is an abstraction; as you dream amid nature, extrapolate art from it, and concentrate on what you will create as a result. Paul Gauguin | Artist",
  "2/25":"I find modernist design boring, but it\'s so much faster! Christine Suewon Lee | Designer",
  "2/26":"I like ruins because what remains is not the total design, but the clarity of thought, the naked structure, the spirit of the thing. Tadao Ando | Architect",
  "2/27":"Art is anything you can get away with. Andy Worhol | Artist",
  "2/28":"Design is where science and art break even. Mieke Gerritzen | Graphic Designer",
  "2/29":"When you don\'t dress like everybody else, you don\'t have to think like everybody else. Iris Apfel | Interior Designer",
  "3/1":"Practice safe design: Use a concept. Petrula Vrontikis | Graphic Designer",
  "3/2":"If Mr. Obama could walk across the Peace Bridge in Hiroshima - whose balustrades were designed by the Japanese-American sculptor Isamu Noguchi as a reminder both of his ties to East and West and of what humans do to one another out of hatred - it would be both a real and a symbolic step toward creating a world that knows no fear of nuclear threat. Issey Miyake | Designer",
  "3/3":"The life of a designer is a life of fight. Fight against the ugliness. Just like a doctor fights against disease. For us, the visual disease is what we have around, and what we try to do is cure it somehow with design.",
  "3/4":"You can\'t really say what is beautiful about a place, but the image of the place will remain vividly with you. Tadao Ando | Architect",
  "3/5":"My work sanitizes it (emotion) but it is also symbolic of commercial art sanitizing human feelings. I think it can be read that way…. People mistake the character of line for the character of art. But it\'s really the position of line that\'s important, or the position of anything, any contrast, not the character of it. Roy Lichtenstein | Artist",
  "3/6":"Style is very personal. It has nothing to do with fashion. Fashion is over quickly. Style is forever. Ralph Lauren | Fashion Designer",
  "3/7":"The first man to compare the cheeks of a young woman to a rose was obviously a poet; the first to repeat it was possibly an idiot.",
  "3/8":"You cannot change how someone thinks, but you can give them a tool to use which will lead them to think differently. Buckminster Fuller | Architect",
  "3/9":"The modern artist is working with space and time, and expressing his feelings rather than illustrating. Jackson Pollock | Artist",
  "3/10":"A house is a machine for living in. Le Corbusier | Architect",
  "3/11":"I don\'t do fashion. I am fashion. Coco Chanel | Fashion Designer",
  "3/12":"I sometimes feel that we are losing an intuitive sense of our own bodies. Toyo Ito | Architect",
  "3/13":"Walk like you have three men walking behind you. Oscar de la Renta | Fashion Designer",
  "3/14":"Prose is architecture, not interior decoration. Ernest Hemingway | Writer",
  "3/15":"I do not create a fashionable aesthetic... I create a style based on life. Issey Miyake | Designer",
  "3/16":"I really believe in the idea of the future. Zaha Hadid | Architect",
  "3/17":"Art is never finished, only abandoned. Leonardo da Vinci | Artist",
  "3/18":"To eliminate the concept of waste means to design things-products, packaging, and systems-from the very beginning on the understanding that waste does not exist. William McDonough | Designer",
  "3/19":"People meet in architecture. Kazuyo Sejima | Architect",
  "3/20":"There are three responses to a piece of design – yes, no, and WOW! Wow is the one to aim for. Milton Glaser | Graphic Designer",
  "3/21":"The painter of the future will be a colorist in a way no one has been before. Vincent van Gogh | Artist",
  "3/22":"Architecture is basically a container of something. I hope they will enjoy not so much the teacup, but the tea. Yoshio Taniguchi | Architect",
  "3/23":"If you give people nothingness, they can ponder what can be achieved from that nothingness. Tadao Ando | Architect",
  "3/24":"Less is more. Mies van der Rohe | Architect",
  "3/25":"We are what we repeatedly do. Excellence then, is not an act, but a habit. Aristotle | Philosopher",
  "3/26":"People tend not to use this word beauty because it\'s not intellectual - but there has to be an overlap between beauty and intellect. Tadao Ando | Architect",
  "3/27":"The longer I live, the more beautiful life becomes. If you foolishly ignore beauty, you will soon find yourself without it. Your life will be impoverished. But if you invest in beauty, it will remain with you all the days of your life. Frank Lloyd Wright | Architect",
  "3/28":"In the big picture, architecture is the art and science of making sure that our cities and buildings fit with the way we want to live our lives. Bjarke Ingels | Architect",
  "3/29":"Design is not for philisophy. Issey Miyake | Designer",
  "3/30":"A designer knows he has achieved perfection not when there is nothing left to add, but when there is nothing left to take away. Antoine de Saint-Exupéry | Writer",
  "3/31":"I would like my architecture to inspire people to use their own resources, to move into the future. Tadao Ando | Architect",
  "4/1":"Digital design is like painting, except the paint never dries. Neville Brody | Graphic Designer",
  "4/2":"The architect represents neither a Dionysian nor an Apollinian condition: here it is the mighty act of will, the will which moves mountains, the intoxication of the strong will, which demands artistic expression. The most powerful men have always inspired the architects; the architect has always been influenced by power. Friedrich Nietzsche | Philosopher",
  "4/3":"Less is a bore. Robert Venturi | Architect",
  "4/4":"Socrates said, \"Know thyself.\" I say, \"Know thy users.\" And guess what? They don\'t think like you do. Joshua Brewer | Graphic Designer",
  "4/5":"I know what women look good in. I don\'t think the rules ever change. Michael Kors | Fashion Designer",
  "4/6":"Our opportunity, as designers, is to learn how to handle the complexity, rather than shy away from it, and to realize that the big art of design is to make complicated things simple. Tim Parsey | Web designer",
  "4/7":"Everything is designed. Few things are designed well. Brian Reed | Comic Book Writer",
  "4/8":"Subversive, ethical, ecological, political, humorous ... this is how I see my duty as a designer. Philippe Starck | Designer",
  "4/9":"To provide meaningful architecture is not to parody history, but to articulate it. Daniel Libeskind | Architect",
  "4/10":"We have to replace beauty, which is a cultural concept, with goodness, which is a humanist concept. Philippe Starck | Designer",
  "4/11":"The life of a designer is one of fight: fight against the ugliness. Massimo Vignelli | Designer",
  "4/12":"Nothing in this world is more simple and more cheap than making cities that provide better for people. Jan Gehl | Architect",
  "4/13":"The public is more familiar with bad design than good design. It is, in effect, conditioned to prefer bad design, because that is what it lives with. The new becomes threatening, the old reassuring. Paul Rand | Graphic Designer",
  "4/14":"People ignore design that ignores people. Frank Chimero | Graphic Designer",
  "4/15":"If you are not able to transmit what you\'re trying to achieve to your collaborators, you will only have minions - or morons. Bjarke Ingels | Architect",
  "4/16":"Every child is an artist. The problem is how to remain an artist once we grow up. Pablo Picasso | Artist",
  "4/17":"Fashion is what you\'re offered four times a year by designers. And style is what you choose. Lauren Hutton | Fashion Designer",
  "4/18":"I understand that, today, some developers are asking architects to design eye-catching, iconic buildings. Fortunately, I\'ve not had that kind of client so far. Fumihiko Maki | Architect",
  "4/19":"The Sun does not realise how wonderful it is until after a room is made. Louis I. Kahn | Architect",
  "4/20":"Design our world so that we have positive social and environmental side effects. Bjarke Ingels | Architect",
  "4/21":"You either know fashion or you don\'t. Anna Wintour | Fashion Designer",
  "4/22":"Good design is all about making other designers feel like idiots because the idea wasn\'t theirs. Frank Chimero | Graphic Designer",
  "4/23":"Design should never say, \"Look at me!\" It should always say, \"Look at this!\" David Craib | Graphic Designer",
  "4/24":"Logic will get you from A to B. Imagination will take you anywhere. Albert Einstein | Scientist",
  "4/25":"Architecture is the will of an epoch translated into space. Mies van der Rohe | Architect",
  "4/26":"You can never take too much care over the choice of your shoes. Too many women think that they are unimportant, but the real proof of an elegant woman is what is on her feet. Christian Dior | Fashion Designer",
  "4/27":"Good design is obvious. Great design is transparent. Joe Sparano | Designer",
  "4/28":"Shoes transform your body language and attitude. They lift you physically and emotionally. Christian Louboutin | Fashion Designer",
  "4/29":"Good architecture is like a good therapy session, a good marriage, a good poem - gently and almost invisibly allowing you to be you, as flawed and as beautiful as you are. Robert Sullivan | Architect",
  "4/30":"In pure architecture the smallest detail should have a meaning or serve a purpose. Augustus W. N. Pugin | Architect",
  "5/1":"The most innovative designers consciously reject the standard option box and cultivate an appetite for thinking wrong. Marty Neumeier | Writer",
  "5/2":"I\'ve noticed the computer sometimes leads to rather bland decision-making; Now, anybody can do a wobbly, blobby building. Peter Cook | Architect",
  "5/3":"What I\'ve done, Coco Chanel would never have done. She would have hated it. Karl Lagerfeld | Fashion Designer",
  "5/4":"I want to make beautiful things, even if nobody cares, as opposed to ugly things. That\'s my intent. Saul Bass | Graphic Designer",
  "5/5":"Creativity takes courage. Henri Matisse | Artist",
  "5/6":"Trendy is the last stage before tacky. Karl Lagerfeld | Fashion Designer",
  "5/7":"Design creates culture. Culture shapes values. Values determine the future. Robert L. Peters | Designer",
  "5/8":"Architecture is the art of how to waste space. Philip Johnson | Architect",
  "5/9":"Walk like you have three men walking behind you. Oscar de la Renta | Fashion Designer",
  "5/10":"I am sure that, as a woman, I can do a very good skyscraper. Zaha Hadid | Architect",
  "5/11":"Fashion is not necessarily about labels. It\'s not about brands. It\'s about something else that comes from within you. Ralph Lauren | Fashion Designer",
  "5/12":"Architecture is a dangerous mix of power and importance. Rem Koolhaas | Architect",
  "5/13":"My juicer is not meant to squeeze lemons; it is meant to start conversations. Philippe Starck | Designer",
  "5/14":"Painting is self-discovery. Every good artist paints what he is. Jackson Pollock | Artist",
  "5/15":"A great building must begin with the immeasurable, must go through measurable means when it is being designed, and in the end must be unmeasured. Louis I. Kahn | Architect",
  "5/16":"A bit of advice, don\'t copy nature too closely. Art is an abstraction; as you dream amid nature, extrapolate art from it, and concentrate on what you will create as a result. Paul Gauguin | Artist",
  "5/17":"I find modernist design boring, but it\'s so much faster! Christine Suewon Lee | Designer",
  "5/18":"I like ruins because what remains is not the total design, but the clarity of thought, the naked structure, the spirit of the thing. Tadao Ando | Architect",
  "5/19":"Art is anything you can get away with. Andy Worhol | Artist",
  "5/20":"Design is where science and art break even. Mieke Gerritzen | Graphic Designer",
  "5/21":"When you don\'t dress like everybody else, you don\'t have to think like everybody else. Iris Apfel | Interior Designer",
  "5/22":"Practice safe design: Use a concept. Petrula Vrontikis | Graphic Designer",
  "5/23":"If Mr. Obama could walk across the Peace Bridge in Hiroshima - whose balustrades were designed by the Japanese-American sculptor Isamu Noguchi as a reminder both of his ties to East and West and of what humans do to one another out of hatred - it would be both a real and a symbolic step toward creating a world that knows no fear of nuclear threat. Issey Miyake | Designer",
  "5/24":"The life of a designer is a life of fight. Fight against the ugliness. Just like a doctor fights against disease. For us, the visual disease is what we have around, and what we try to do is cure it somehow with design.",
  "5/25":"You can\'t really say what is beautiful about a place, but the image of the place will remain vividly with you. Tadao Ando | Architect",
  "5/26":"My work sanitizes it (emotion) but it is also symbolic of commercial art sanitizing human feelings. I think it can be read that way…. People mistake the character of line for the character of art. But it\'s really the position of line that\'s important, or the position of anything, any contrast, not the character of it. Roy Lichtenstein | Artist",
  "5/27":"Style is very personal. It has nothing to do with fashion. Fashion is over quickly. Style is forever. Ralph Lauren | Fashion Designer",
  "5/28":"The first man to compare the cheeks of a young woman to a rose was obviously a poet; the first to repeat it was possibly an idiot.",
  "5/29":"You cannot change how someone thinks, but you can give them a tool to use which will lead them to think differently. Buckminster Fuller | Architect",
  "5/30":"The modern artist is working with space and time, and expressing his feelings rather than illustrating. Jackson Pollock | Artist",
  "5/31":"A house is a machine for living in. Le Corbusier | Architect",
  "6/1":"I don\'t do fashion. I am fashion. Coco Chanel | Fashion Designer",
  "6/2":"I sometimes feel that we are losing an intuitive sense of our own bodies. Toyo Ito | Architect",
  "6/3":"Design needs to be plugged into human behavior. Design dissolves in behavior. Naoto Fukasawa | Designer",
  "6/4":"Prose is architecture, not interior decoration. Ernest Hemingway | Writer",
  "6/5":"I do not create a fashionable aesthetic... I create a style based on life. Issey Miyake | Designer",
  "6/6":"I really believe in the idea of the future. Zaha Hadid | Architect",
  "6/7":"Art is never finished, only abandoned. Leonardo da Vinci | Artist",
  "6/8":"To eliminate the concept of waste means to design things-products, packaging, and systems-from the very beginning on the understanding that waste does not exist. William McDonough | Designer",
  "6/9":"People meet in architecture. Kazuyo Sejima | Architect",
  "6/10":"There are three responses to a piece of design – yes, no, and WOW! Wow is the one to aim for. Milton Glaser | Graphic Designer",
  "6/11":"The painter of the future will be a colorist in a way no one has been before. Vincent van Gogh | Artist",
  "6/12":"Architecture is basically a container of something. I hope they will enjoy not so much the teacup, but the tea. Yoshio Taniguchi | Architect",
  "6/13":"If you give people nothingness, they can ponder what can be achieved from that nothingness. Tadao Ando | Architect",
  "6/14":"Less is more. Mies van der Rohe | Architect",
  "6/15":"We are what we repeatedly do. Excellence then, is not an act, but a habit. Aristotle | Philosopher",
  "6/16":"People tend not to use this word beauty because it\'s not intellectual - but there has to be an overlap between beauty and intellect. Tadao Ando | Architect",
  "6/17":"The longer I live, the more beautiful life becomes. If you foolishly ignore beauty, you will soon find yourself without it. Your life will be impoverished. But if you invest in beauty, it will remain with you all the days of your life. Frank Lloyd Wright | Architect",
  "6/18":"In the big picture, architecture is the art and science of making sure that our cities and buildings fit with the way we want to live our lives. Bjarke Ingels | Architect",
  "6/19":"Design is not for philisophy. Issey Miyake | Designer",
  "6/20":"A designer knows he has achieved perfection not when there is nothing left to add, but when there is nothing left to take away. Antoine de Saint-Exupéry | Writer",
  "6/21":"I would like my architecture to inspire people to use their own resources, to move into the future. Tadao Ando | Architect",
  "6/22":"Digital design is like painting, except the paint never dries. Neville Brody | Graphic Designer",
  "6/23":"The architect represents neither a Dionysian nor an Apollinian condition: here it is the mighty act of will, the will which moves mountains, the intoxication of the strong will, which demands artistic expression. The most powerful men have always inspired the architects; the architect has always been influenced by power. Friedrich Nietzsche | Philosopher",
  "6/24":"Less is a bore. Robert Venturi | Architect",
  "6/25":"Socrates said, \"Know thyself.\" I say, \"Know thy users.\" And guess what? They don\'t think like you do. Joshua Brewer | Graphic Designer",
  "6/26":"I know what women look good in. I don\'t think the rules ever change. Michael Kors | Fashion Designer",
  "6/27":"Our opportunity, as designers, is to learn how to handle the complexity, rather than shy away from it, and to realize that the big art of design is to make complicated things simple. Tim Parsey | Web designer",
  "6/28":"Everything is designed. Few things are designed well. Brian Reed | Comic Book Writer",
  "6/29":"Subversive, ethical, ecological, political, humorous ... this is how I see my duty as a designer. Philippe Starck | Designer",
  "6/30":"To provide meaningful architecture is not to parody history, but to articulate it. Daniel Libeskind | Architect",
  "7/1":"We have to replace beauty, which is a cultural concept, with goodness, which is a humanist concept. Philippe Starck | Designer",
  "7/2":"The life of a designer is one of fight: fight against the ugliness. Massimo Vignelli | Designer",
  "7/3":"Nothing in this world is more simple and more cheap than making cities that provide better for people. Jan Gehl | Architect",
  "7/4":"The public is more familiar with bad design than good design. It is, in effect, conditioned to prefer bad design, because that is what it lives with. The new becomes threatening, the old reassuring. Paul Rand | Graphic Designer",
  "7/5":"People ignore design that ignores people. Frank Chimero | Graphic Designer",
  "7/6":"If you are not able to transmit what you\'re trying to achieve to your collaborators, you will only have minions - or morons. Bjarke Ingels | Architect",
  "7/7":"Every child is an artist. The problem is how to remain an artist once we grow up. Pablo Picasso | Artist",
  "7/8":"Fashion is what you\'re offered four times a year by designers. And style is what you choose. Lauren Hutton | Fashion Designer",
  "7/9":"I understand that, today, some developers are asking architects to design eye-catching, iconic buildings. Fortunately, I\'ve not had that kind of client so far. Fumihiko Maki | Architect",
  "7/10":"The Sun does not realise how wonderful it is until after a room is made. Louis I. Kahn | Architect",
  "7/11":"Design our world so that we have positive social and environmental side effects. Bjarke Ingels | Architect",
  "7/12":"You either know fashion or you don\'t. Anna Wintour | Fashion Designer",
  "7/13":"Good design is all about making other designers feel like idiots because the idea wasn\'t theirs. Frank Chimero | Graphic Designer",
  "7/14":"Design should never say, \"Look at me!\" It should always say, \"Look at this!\" David Craib | Graphic Designer",
  "7/15":"Logic will get you from A to B. Imagination will take you anywhere. Albert Einstein | Scientist",
  "7/16":"Architecture is the will of an epoch translated into space. Mies van der Rohe | Architect",
  "7/17":"You can never take too much care over the choice of your shoes. Too many women think that they are unimportant, but the real proof of an elegant woman is what is on her feet. Christian Dior | Fashion Designer",
  "7/18":"Good design is obvious. Great design is transparent. Joe Sparano | Designer",
  "7/19":"Shoes transform your body language and attitude. They lift you physically and emotionally. Christian Louboutin | Fashion Designer",
  "7/20":"Good architecture is like a good therapy session, a good marriage, a good poem - gently and almost invisibly allowing you to be you, as flawed and as beautiful as you are. Robert Sullivan | Architect",
  "7/21":"In pure architecture the smallest detail should have a meaning or serve a purpose. Augustus W. N. Pugin | Architect",
  "7/22":"The most innovative designers consciously reject the standard option box and cultivate an appetite for thinking wrong. Marty Neumeier | Writer",
  "7/23":"I\'ve noticed the computer sometimes leads to rather bland decision-making; Now, anybody can do a wobbly, blobby building. Peter Cook | Architect",
  "7/24":"What I\'ve done, Coco Chanel would never have done. She would have hated it. Karl Lagerfeld | Fashion Designer",
  "7/25":"I want to make beautiful things, even if nobody cares, as opposed to ugly things. That\'s my intent. Saul Bass | Graphic Designer",
  "7/26":"Creativity takes courage. Henri Matisse | Artist",
  "7/27":"Trendy is the last stage before tacky. Karl Lagerfeld | Fashion Designer",
  "7/28":"Design creates culture. Culture shapes values. Values determine the future. Robert L. Peters | Designer",
  "7/29":"Architecture is the art of how to waste space. Philip Johnson | Architect",
  "7/30":"Walk like you have three men walking behind you. Oscar de la Renta | Fashion Designer",
  "7/31":"I am sure that, as a woman, I can do a very good skyscraper. Zaha Hadid | Architect",
  "8/1":"Fashion is not necessarily about labels. It\'s not about brands. It\'s about something else that comes from within you. Ralph Lauren | Fashion Designer",
  "8/2":"Architecture is a dangerous mix of power and importance. Rem Koolhaas | Architect",
  "8/3":"My juicer is not meant to squeeze lemons; it is meant to start conversations. Philippe Starck | Designer",
  "8/4":"Painting is self-discovery. Every good artist paints what he is. Jackson Pollock | Artist",
  "8/5":"A great building must begin with the immeasurable, must go through measurable means when it is being designed, and in the end must be unmeasured. Louis I. Kahn | Architect",
  "8/6":"A bit of advice, don\'t copy nature too closely. Art is an abstraction; as you dream amid nature, extrapolate art from it, and concentrate on what you will create as a result. Paul Gauguin | Artist",
  "8/7":"I find modernist design boring, but it\'s so much faster! Christine Suewon Lee | Designer",
  "8/8":"I like ruins because what remains is not the total design, but the clarity of thought, the naked structure, the spirit of the thing. Tadao Ando | Architect",
  "8/9":"Art is anything you can get away with. Andy Worhol | Artist",
  "8/10":"Design is where science and art break even. Mieke Gerritzen | Graphic Designer",
  "8/11":"When you don\'t dress like everybody else, you don\'t have to think like everybody else. Iris Apfel | Interior Designer",
  "8/12":"Practice safe design: Use a concept. Petrula Vrontikis | Graphic Designer",
  "8/13":"If Mr. Obama could walk across the Peace Bridge in Hiroshima - whose balustrades were designed by the Japanese-American sculptor Isamu Noguchi as a reminder both of his ties to East and West and of what humans do to one another out of hatred - it would be both a real and a symbolic step toward creating a world that knows no fear of nuclear threat. Issey Miyake | Designer",
  "8/14":"The life of a designer is a life of fight. Fight against the ugliness. Just like a doctor fights against disease. For us, the visual disease is what we have around, and what we try to do is cure it somehow with design.",
  "8/15":"You can\'t really say what is beautiful about a place, but the image of the place will remain vividly with you. Tadao Ando | Architect",
  "8/16":"My work sanitizes it (emotion) but it is also symbolic of commercial art sanitizing human feelings. I think it can be read that way…. People mistake the character of line for the character of art. But it\'s really the position of line that\'s important, or the position of anything, any contrast, not the character of it. Roy Lichtenstein | Artist",
  "8/17":"Style is very personal. It has nothing to do with fashion. Fashion is over quickly. Style is forever. Ralph Lauren | Fashion Designer",
  "8/18":"The first man to compare the cheeks of a young woman to a rose was obviously a poet; the first to repeat it was possibly an idiot.",
  "8/19":"You cannot change how someone thinks, but you can give them a tool to use which will lead them to think differently. Buckminster Fuller | Architect",
  "8/20":"The modern artist is working with space and time, and expressing his feelings rather than illustrating. Jackson Pollock | Artist",
  "8/21":"A house is a machine for living in. Le Corbusier | Architect",
  "8/22":"I don\'t do fashion. I am fashion. Coco Chanel | Fashion Designer",
  "8/23":"I sometimes feel that we are losing an intuitive sense of our own bodies. Toyo Ito | Architect",
  "8/24":"Design needs to be plugged into human behavior. Design dissolves in behavior. Naoto Fukasawa | Designer",
  "8/25":"Prose is architecture, not interior decoration. Ernest Hemingway | Writer",
  "8/26":"I do not create a fashionable aesthetic... I create a style based on life. Issey Miyake | Designer",
  "8/27":"I really believe in the idea of the future. Zaha Hadid | Architect",
  "8/28":"Art is never finished, only abandoned. Leonardo da Vinci | Artist",
  "8/29":"To eliminate the concept of waste means to design things-products, packaging, and systems-from the very beginning on the understanding that waste does not exist. William McDonough | Designer",
  "8/30":"People meet in architecture. Kazuyo Sejima | Architect",
  "8/31":"There are three responses to a piece of design – yes, no, and WOW! Wow is the one to aim for. Milton Glaser | Graphic Designer",
  "9/1":"The painter of the future will be a colorist in a way no one has been before. Vincent van Gogh | Artist",
  "9/2":"Architecture is basically a container of something. I hope they will enjoy not so much the teacup, but the tea. Yoshio Taniguchi | Architect",
  "9/3":"If you give people nothingness, they can ponder what can be achieved from that nothingness. Tadao Ando | Architect",
  "9/4":"Less is more. Mies van der Rohe | Architect",
  "9/5":"We are what we repeatedly do. Excellence then, is not an act, but a habit. Aristotle | Philosopher",
  "9/6":"People tend not to use this word beauty because it\'s not intellectual - but there has to be an overlap between beauty and intellect. Tadao Ando | Architect",
  "9/7":"The longer I live, the more beautiful life becomes. If you foolishly ignore beauty, you will soon find yourself without it. Your life will be impoverished. But if you invest in beauty, it will remain with you all the days of your life. Frank Lloyd Wright | Architect",
  "9/8":"In the big picture, architecture is the art and science of making sure that our cities and buildings fit with the way we want to live our lives. Bjarke Ingels | Architect",
  "9/9":"Design is not for philisophy. Issey Miyake | Designer",
  "9/10":"A designer knows he has achieved perfection not when there is nothing left to add, but when there is nothing left to take away. Antoine de Saint-Exupéry | Writer",
  "9/11":"I would like my architecture to inspire people to use their own resources, to move into the future. Tadao Ando | Architect",
  "9/12":"Digital design is like painting, except the paint never dries. Neville Brody | Graphic Designer",
  "9/13":"The architect represents neither a Dionysian nor an Apollinian condition: here it is the mighty act of will, the will which moves mountains, the intoxication of the strong will, which demands artistic expression. The most powerful men have always inspired the architects; the architect has always been influenced by power. Friedrich Nietzsche | Philosopher",
  "9/14":"Less is a bore. Robert Venturi | Architect",
  "9/15":"Socrates said, \"Know thyself.\" I say, \"Know thy users.\" And guess what? They don\'t think like you do. Joshua Brewer | Graphic Designer",
  "9/16":"I know what women look good in. I don\'t think the rules ever change. Michael Kors | Fashion Designer",
  "9/17":"Our opportunity, as designers, is to learn how to handle the complexity, rather than shy away from it, and to realize that the big art of design is to make complicated things simple. Tim Parsey | Web designer",
  "9/18":"Everything is designed. Few things are designed well. Brian Reed | Comic Book Writer",
  "9/19":"Subversive, ethical, ecological, political, humorous ... this is how I see my duty as a designer. Philippe Starck | Designer",
  "9/20":"To provide meaningful architecture is not to parody history, but to articulate it. Daniel Libeskind | Architect",
  "9/21":"We have to replace beauty, which is a cultural concept, with goodness, which is a humanist concept. Philippe Starck | Designer",
  "9/22":"The life of a designer is one of fight: fight against the ugliness. Massimo Vignelli | Designer",
  "9/23":"Nothing in this world is more simple and more cheap than making cities that provide better for people. Jan Gehl | Architect",
  "9/24":"The public is more familiar with bad design than good design. It is, in effect, conditioned to prefer bad design, because that is what it lives with. The new becomes threatening, the old reassuring. Paul Rand | Graphic Designer",
  "9/25":"People ignore design that ignores people. Frank Chimero | Graphic Designer",
  "9/26":"If you are not able to transmit what you\'re trying to achieve to your collaborators, you will only have minions - or morons. Bjarke Ingels | Architect",
  "9/27":"Every child is an artist. The problem is how to remain an artist once we grow up. Pablo Picasso | Artist",
  "9/28":"Fashion is what you\'re offered four times a year by designers. And style is what you choose. Lauren Hutton | Fashion Designer",
  "9/29":"I understand that, today, some developers are asking architects to design eye-catching, iconic buildings. Fortunately, I\'ve not had that kind of client so far. Fumihiko Maki | Architect",
  "9/30":"The Sun does not realise how wonderful it is until after a room is made. Louis I. Kahn | Architect",
  "10/1":"Design our world so that we have positive social and environmental side effects. Bjarke Ingels | Architect",
  "10/2":"You either know fashion or you don\'t. Anna Wintour | Fashion Designer",
  "10/3":"Good design is all about making other designers feel like idiots because the idea wasn\'t theirs. Frank Chimero | Graphic Designer",
  "10/4":"Design should never say, \"Look at me!\" It should always say, \"Look at this!\" David Craib | Graphic Designer",
  "10/5":"Logic will get you from A to B. Imagination will take you anywhere. Albert Einstein | Scientist",
  "10/6":"Architecture is the will of an epoch translated into space. Mies van der Rohe | Architect",
  "10/7":"You can never take too much care over the choice of your shoes. Too many women think that they are unimportant, but the real proof of an elegant woman is what is on her feet. Christian Dior | Fashion Designer",
  "10/8":"Good design is obvious. Great design is transparent. Joe Sparano | Designer",
  "10/9":"Shoes transform your body language and attitude. They lift you physically and emotionally. Christian Louboutin | Fashion Designer",
  "10/10":"Good architecture is like a good therapy session, a good marriage, a good poem - gently and almost invisibly allowing you to be you, as flawed and as beautiful as you are. Robert Sullivan | Architect",
  "10/11":"In pure architecture the smallest detail should have a meaning or serve a purpose. Augustus W. N. Pugin | Architect",
  "10/12":"The most innovative designers consciously reject the standard option box and cultivate an appetite for thinking wrong. Marty Neumeier | Writer",
  "10/13":"I\'ve noticed the computer sometimes leads to rather bland decision-making; Now, anybody can do a wobbly, blobby building. Peter Cook | Architect",
  "10/14":"What I\'ve done, Coco Chanel would never have done. She would have hated it. Karl Lagerfeld | Fashion Designer",
  "10/15":"I want to make beautiful things, even if nobody cares, as opposed to ugly things. That\'s my intent. Saul Bass | Graphic Designer",
  "10/16":"Creativity takes courage. Henri Matisse | Artist",
  "10/17":"Trendy is the last stage before tacky. Karl Lagerfeld | Fashion Designer",
  "10/18":"Design creates culture. Culture shapes values. Values determine the future. Robert L. Peters | Designer",
  "10/19":"Architecture is the art of how to waste space. Philip Johnson | Architect",
  "10/20":"Walk like you have three men walking behind you. Oscar de la Renta | Fashion Designer",
  "10/21":"I am sure that, as a woman, I can do a very good skyscraper. Zaha Hadid | Architect",
  "10/22":"Fashion is not necessarily about labels. It\'s not about brands. It\'s about something else that comes from within you. Ralph Lauren | Fashion Designer",
  "10/23":"Architecture is a dangerous mix of power and importance. Rem Koolhaas | Architect",
  "10/24":"My juicer is not meant to squeeze lemons; it is meant to start conversations. Philippe Starck | Designer",
  "10/25":"Painting is self-discovery. Every good artist paints what he is. Jackson Pollock | Artist",
  "10/26":"A great building must begin with the immeasurable, must go through measurable means when it is being designed, and in the end must be unmeasured. Louis I. Kahn | Architect",
  "10/27":"A bit of advice, don\'t copy nature too closely. Art is an abstraction; as you dream amid nature, extrapolate art from it, and concentrate on what you will create as a result. Paul Gauguin | Artist",
  "10/28":"I find modernist design boring, but it\'s so much faster! Christine Suewon Lee | Designer",
  "10/29":"I like ruins because what remains is not the total design, but the clarity of thought, the naked structure, the spirit of the thing. Tadao Ando | Architect",
  "10/30":"Art is anything you can get away with. Andy Worhol | Artist",
  "10/31":"Design is where science and art break even. Mieke Gerritzen | Graphic Designer",
  "11/1":"When you don\'t dress like everybody else, you don\'t have to think like everybody else. Iris Apfel | Interior Designer",
  "11/2":"Practice safe design: Use a concept. Petrula Vrontikis | Graphic Designer",
  "11/3":"If Mr. Obama could walk across the Peace Bridge in Hiroshima - whose balustrades were designed by the Japanese-American sculptor Isamu Noguchi as a reminder both of his ties to East and West and of what humans do to one another out of hatred - it would be both a real and a symbolic step toward creating a world that knows no fear of nuclear threat. Issey Miyake | Designer",
  "11/4":"The life of a designer is a life of fight. Fight against the ugliness. Just like a doctor fights against disease. For us, the visual disease is what we have around, and what we try to do is cure it somehow with design.",
  "11/5":"You can\'t really say what is beautiful about a place, but the image of the place will remain vividly with you. Tadao Ando | Architect",
  "11/6":"My work sanitizes it (emotion) but it is also symbolic of commercial art sanitizing human feelings. I think it can be read that way…. People mistake the character of line for the character of art. But it\'s really the position of line that\'s important, or the position of anything, any contrast, not the character of it. Roy Lichtenstein | Artist",
  "11/7":"Style is very personal. It has nothing to do with fashion. Fashion is over quickly. Style is forever. Ralph Lauren | Fashion Designer",
  "11/8":"The first man to compare the cheeks of a young woman to a rose was obviously a poet; the first to repeat it was possibly an idiot.",
  "11/9":"You cannot change how someone thinks, but you can give them a tool to use which will lead them to think differently. Buckminster Fuller | Architect",
  "11/10":"The modern artist is working with space and time, and expressing his feelings rather than illustrating. Jackson Pollock | Artist",
  "11/11":"A house is a machine for living in. Le Corbusier | Architect",
  "11/12":"I don\'t do fashion. I am fashion. Coco Chanel | Fashion Designer",
  "11/13":"I sometimes feel that we are losing an intuitive sense of our own bodies. Toyo Ito | Architect",
  "11/14":"Design needs to be plugged into human behavior. Design dissolves in behavior. Naoto Fukasawa | Designer",
  "11/15":"Prose is architecture, not interior decoration. Ernest Hemingway | Writer",
  "11/16":"I do not create a fashionable aesthetic... I create a style based on life. Issey Miyake | Designer",
  "11/17":"I really believe in the idea of the future. Zaha Hadid | Architect",
  "11/18":"Art is never finished, only abandoned. Leonardo da Vinci | Artist",
  "11/19":"To eliminate the concept of waste means to design things-products, packaging, and systems-from the very beginning on the understanding that waste does not exist. William McDonough | Designer",
  "11/20":"People meet in architecture. Kazuyo Sejima | Architect",
  "11/21":"There are three responses to a piece of design – yes, no, and WOW! Wow is the one to aim for. Milton Glaser | Graphic Designer",
  "11/22":"The painter of the future will be a colorist in a way no one has been before. Vincent van Gogh | Artist",
  "11/23":"Architecture is basically a container of something. I hope they will enjoy not so much the teacup, but the tea. Yoshio Taniguchi | Architect",
  "11/24":"If you give people nothingness, they can ponder what can be achieved from that nothingness. Tadao Ando | Architect",
  "11/25":"Less is more. Mies van der Rohe | Architect",
  "11/26":"We are what we repeatedly do. Excellence then, is not an act, but a habit. Aristotle | Philosopher",
  "11/27":"People tend not to use this word beauty because it\'s not intellectual - but there has to be an overlap between beauty and intellect. Tadao Ando | Architect",
  "11/28":"The longer I live, the more beautiful life becomes. If you foolishly ignore beauty, you will soon find yourself without it. Your life will be impoverished. But if you invest in beauty, it will remain with you all the days of your life. Frank Lloyd Wright | Architect",
  "11/29":"In the big picture, architecture is the art and science of making sure that our cities and buildings fit with the way we want to live our lives. Bjarke Ingels | Architect",
  "11/30":"Design is not for philisophy. Issey Miyake | Designer",
  "12/1":"A designer knows he has achieved perfection not when there is nothing left to add, but when there is nothing left to take away. Antoine de Saint-Exupéry | Writer",
  "12/2":"I would like my architecture to inspire people to use their own resources, to move into the future. Tadao Ando | Architect",
  "12/3":"Digital design is like painting, except the paint never dries. Neville Brody | Graphic Designer",
  "12/4":"The architect represents neither a Dionysian nor an Apollinian condition: here it is the mighty act of will, the will which moves mountains, the intoxication of the strong will, which demands artistic expression. The most powerful men have always inspired the architects; the architect has always been influenced by power. Friedrich Nietzsche | Philosopher",
  "12/5":"Less is a bore. Robert Venturi | Architect",
  "12/6":"Socrates said, \"Know thyself.\" I say, \"Know thy users.\" And guess what? They don\'t think like you do. Joshua Brewer | Graphic Designer",
  "12/7":"I know what women look good in. I don\'t think the rules ever change. Michael Kors | Fashion Designer",
  "12/8":"Our opportunity, as designers, is to learn how to handle the complexity, rather than shy away from it, and to realize that the big art of design is to make complicated things simple. Tim Parsey | Web designer",
  "12/9":"Everything is designed. Few things are designed well. Brian Reed | Comic Book Writer",
  "12/10":"Subversive, ethical, ecological, political, humorous ... this is how I see my duty as a designer. Philippe Starck | Designer",
  "12/11":"To provide meaningful architecture is not to parody history, but to articulate it. Daniel Libeskind | Architect",
  "12/12":"We have to replace beauty, which is a cultural concept, with goodness, which is a humanist concept. Philippe Starck | Designer",
  "12/13":"The life of a designer is one of fight: fight against the ugliness. Massimo Vignelli | Designer",
  "12/14":"Nothing in this world is more simple and more cheap than making cities that provide better for people. Jan Gehl | Architect",
  "12/15":"The public is more familiar with bad design than good design. It is, in effect, conditioned to prefer bad design, because that is what it lives with. The new becomes threatening, the old reassuring. Paul Rand | Graphic Designer",
  "12/16":"People ignore design that ignores people. Frank Chimero | Graphic Designer",
  "12/17":"If you are not able to transmit what you\'re trying to achieve to your collaborators, you will only have minions - or morons. Bjarke Ingels | Architect",
  "12/18":"Every child is an artist. The problem is how to remain an artist once we grow up. Pablo Picasso | Artist",
  "12/19":"Fashion is what you\'re offered four times a year by designers. And style is what you choose. Lauren Hutton | Fashion Designer",
  "12/20":"I understand that, today, some developers are asking architects to design eye-catching, iconic buildings. Fortunately, I\'ve not had that kind of client so far. Fumihiko Maki | Architect",
  "12/21":"The Sun does not realise how wonderful it is until after a room is made. Louis I. Kahn | Architect",
  "12/22":"Design our world so that we have positive social and environmental side effects. Bjarke Ingels | Architect",
  "12/23":"You either know fashion or you don\'t. Anna Wintour | Fashion Designer",
  "12/24":"Good design is all about making other designers feel like idiots because the idea wasn\'t theirs. Frank Chimero | Graphic Designer",
  "12/25":"Design should never say, \"Look at me!\" It should always say, \"Look at this!\" David Craib | Graphic Designer",
  "12/26":"Logic will get you from A to B. Imagination will take you anywhere. Albert Einstein | Scientist",
  "12/27":"Architecture is the will of an epoch translated into space. Mies van der Rohe | Architect",
  "12/28":"You can never take too much care over the choice of your shoes. Too many women think that they are unimportant, but the real proof of an elegant woman is what is on her feet. Christian Dior | Fashion Designer",
  "12/29":"Good design is obvious. Great design is transparent. Joe Sparano | Designer",
  "12/30":"Shoes transform your body language and attitude. They lift you physically and emotionally. Christian Louboutin | Fashion Designer",
  "12/31":"Good architecture is like a good therapy session, a good marriage, a good poem - gently and almost invisibly allowing you to be you, as flawed and as beautiful as you are. Robert Sullivan | Architect",
}
